### ISSUE TITLE
[Task]: Fix branches merging issues

### ISSUE THREAD

**Issue by kingjia90** [pimcore/payment-provider-paypal-smart-payment-button#12]
In `2.x` the `1.0.3` changes are missing, 
https://github.com/pimcore/payment-provider-paypal-smart-payment-button/compare/2.x...1.0
https://github.com/pimcore/payment-provider-paypal-smart-payment-button/compare/v1.0.2...v1.0.3

need to pull 1.0 into 2.x, preferrably after phpstan #11  got merged

**Comment by dvesh3** [comment]
@kingjia90 1.0 is merged into 2.x
