### ISSUE TITLE
Prepare for Symfony 6 upgrade

### ISSUE THREAD

**Issue by dvesh3** [pimcore/payment-provider-paypal-smart-payment-button#4]
### Feature description

Related to https://github.com/pimcore/pimcore/issues/13242

**Comment by kingjia90** [comment]
It seems there's nothing to change to support 6

**Comment by dvesh3** [comment]
@kingjia90 at least we should update `pimcore/pimcore` requirements to support 10.5 & 11 version here https://github.com/pimcore/payment-provider-paypal-smart-payment-button/blob/1.x/composer.json#L11
